# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20170220_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Climb')),
            ],
        ),
    ]
