# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_remove_climb_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
