# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20170221_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb',
            name='stars',
            field=models.CharField(blank=True, choices=[('3', '3'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=255),
        ),
        migrations.AlterField(
            model_name='climb',
            name='grade',
            field=models.CharField(choices=[('8b', '8b'), ('8a+', '8a+'), ('8a', '8a'), ('7c+', '7c+'), ('7c', '7c'), ('7b+', '7b+'), ('7b', '7b'), ('7a+', '7a+'), ('7a', '7a'), ('6c+', '6c+'), ('6c', '6c'), ('6b+', '6b+')], max_length=255),
        ),
    ]
