# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20170221_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb',
            name='global_repeats',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
