# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_climb_global_repeats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='attempts',
            field=models.CharField(blank=True, choices=[('More than 3', 'More than 3'), ('3rd Go', '3rd Go'), ('2nd Go', '2nd Go'), ('Flash', 'Flash')], max_length=255),
        ),
        migrations.AddField(
            model_name='userlog',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='personal_grade',
            field=models.CharField(choices=[('8b', '8b'), ('8a+', '8a+'), ('8a', '8a'), ('7c+', '7c+'), ('7c', '7c'), ('7b+', '7b+'), ('7b', '7b'), ('7a+', '7a+'), ('7a', '7a'), ('6c+', '6c+'), ('6c', '6c'), ('6b+', '6b+')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlog',
            name='stars',
            field=models.CharField(blank=True, choices=[('3', '3'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=9999),
        ),
    ]
