# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_auto_20170221_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
