# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_auto_20170222_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb',
            name='canvas',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
