# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_climb_canvas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='canvas',
            field=models.BooleanField(default=False),
        ),
    ]
