# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_auto_20170222_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
