# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0021_auto_20170222_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='stars',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('1', '1'), ('0', '0')], max_length=255),
        ),
    ]
