# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0030_auto_20170224_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='stars',
            field=models.IntegerField(choices=[(3, '3'), (2, '2'), (1, '1'), (0, '0')], null=True),
        ),
    ]
