# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0036_auto_20170226_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='date',
        ),
        migrations.AddField(
            model_name='userlog',
            name='datepicker',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climb',
            name='grade',
            field=models.IntegerField(choices=[(13, '8b'), (12, '8a+'), (11, '8a'), (10, '7c+'), (9, '7c'), (8.25, '7b+'), (7.75, '7b'), (7, '7a+'), (6, '7a'), (5, '6c+'), (4, '6c'), (3, '6b+')], verbose_name='Global Grade'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ape_index',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ape Index'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='height',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='moonboardlocation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Moonboard Location'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='weight',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
