# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0037_auto_20170226_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='datepicker',
        ),
        migrations.AddField(
            model_name='userlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
