# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0038_auto_20170226_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
