# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0042_auto_20170226_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='grade',
            field=models.IntegerField(choices=[(13, '8b'), (12, '8a+'), (11, '8a'), (10, '7c+'), (9, '7c'), (8, '7b+'), (7, '7b'), (6, '7a+'), (5, '7a'), (4, '6c+'), (3, '6c'), (2, '6b+')], verbose_name='Global Grade'),
        ),
    ]
