# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0043_auto_20170226_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='sends',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climb',
            name='grade',
            field=models.IntegerField(choices=[(13, '8b'), (12, '8a+'), (11, '8a'), (10, '7c+'), (9, '7c'), (8, '7b+'), (7, '7b'), (6, '7a+'), (5, '7a'), (4, '6c+'), (3, '6c'), (2, '6b+')]),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='personal_grade',
            field=models.IntegerField(blank=True, choices=[(13, '8b'), (12, '8a+'), (11, '8a'), (10, '7c+'), (9, '7c'), (8, '7b+'), (7, '7b'), (6, '7a+'), (5, '7a'), (4, '6c+'), (3, '6c'), (2, '6b+')]),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(3, '3'), (2, '2'), (1, '1'), (0, '0')]),
        ),
    ]
