# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0044_auto_20170226_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='sends',
            field=models.IntegerField(),
        ),
    ]
