# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0045_auto_20170226_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='sends',
            field=models.IntegerField(editable=False),
        ),
    ]
