# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0046_auto_20170226_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='sends',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
