# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0047_auto_20170226_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='sends',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='a',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='aplusb',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='b',
            field=models.IntegerField(null=True),
        ),
    ]
