# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0048_auto_20170226_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='a',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='aplusb',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='b',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
