# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0049_auto_20170226_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='aplusb',
            new_name='sends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='a',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='b',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='checkid',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
