# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0050_auto_20170226_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='sevencpoints',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
