# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0052_auto_20170227_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='eightaplussends',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='eightbsends',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenaplussends',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenasends',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenbplussends',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenbsends',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevencplussends',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixbplussends',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixcplussends',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixcsends',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
