# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0053_auto_20170227_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='eightasends',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
