# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0054_userdetails_eightasends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='global_repeats',
            field=models.IntegerField(blank=True, max_length=255),
        ),
    ]
