# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0060_userdetails_sevencsends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='eightaplussends',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='eightasends',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='eightbsends',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenaplussends',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenasends',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenbsends',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevencplussends',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixbplussends',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixcplussends',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixcsends',
            field=models.IntegerField(null=True),
        ),
    ]
