# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0061_auto_20170302_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='sevenbplussends',
            field=models.IntegerField(null=True),
        ),
    ]
