# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0062_userdetails_sevenbplussends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='eightaplussendsmonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='eightasendsmonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='eightbsendsmonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenaplussendsmonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenasendsmonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenbplussendsmonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenbsendsmonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevencplussendsmonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevencsendsmonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixbplussendsmonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixcplussendsmonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixcsendsmonth',
            field=models.IntegerField(null=True),
        ),
    ]
