# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0064_auto_20170302_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='eightaplussends',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='eightaplussendsmonth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='eightasends',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='eightasendsmonth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='eightbsends',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='eightbsendsmonth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenaplussends',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenaplussendsmonth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenasends',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenasendsmonth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenbplussends',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenbplussendsmonth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenbsends',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevenbsendsmonth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevencplussends',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevencplussendsmonth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevencsends',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sevencsendsmonth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixbplussends',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixbplussendsmonth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixcplussends',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixcplussendsmonth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixcsends',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sixcsendsmonth',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
