# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0065_auto_20170302_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='eightaplussends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='eightaplussendsmonth',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='eightasends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='eightasendsmonth',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='eightbsends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='eightbsendsmonth',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sevenaplussends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sevenaplussendsmonth',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sevenasends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sevenasendsmonth',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sevenbplussends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sevenbplussendsmonth',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sevenbsends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sevenbsendsmonth',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sevencplussends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sevencplussendsmonth',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sevencsends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sevencsendsmonth',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sixbplussends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sixbplussendsmonth',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sixcplussends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sixcplussendsmonth',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sixcsends',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='sixcsendsmonth',
        ),
    ]
